/**
    식품의 정보
    FOOD_PRODUCT 
    
    식품의 주문 정보 - 공장ID, 창고ID 같은게 있음
    FOOD_ORDER
    
    생산일자가 -> 2022년 5월인 식품 (JOIN)
    총매출 : 이거는 GROUP BY 해야함
**/
SELECT
    FOOD_PRODUCT.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT
JOIN FOOD_ORDER ON FOOD_PRODUCT.PRODUCT_ID = FOOD_ORDER.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY FOOD_PRODUCT.PRODUCT_ID
ORDER BY SUM(PRICE * AMOUNT) DESC, FOOD_PRODUCT.PRODUCT_ID 