/**
    USER_INFO : 회원 정보
    ONLINE_SALE : 온라인 상품 판매 정보
    
    USER_INFO 테이블과 ONLINE_SALE 테이블에서 
    2021년에 가입한 회원들중
    상품을 구매한 회원수, 상품을 구매한 회원의 비율
    년, 월 별로 출력
    (판매데이터 년 월 기준)
    
    소수점 두번째자리 반올림
    전체 결과 년을 기준으로 오름차순
    같으면 월 기준
**/

SELECT
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_INFO.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_INFO.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)=2021),1) AS PUCHASED_RATIO
FROM USER_INFO
JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE YEAR(JOINED)=2021
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)
ORDER BY YEAR(ONLINE_SALE.SALES_DATE), MONTH(ONLINE_SALE.SALES_DATE)