/**
    16:07 ~ 
    
    CAR_RENTAL_COMPANY_CAR : 대여 중인 자동차
    CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록 정보
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 자동차 종류 별 대여 기간 종류 별 할인 정책 정보
    
    할인율이 적용되는 대여 기간 종류로는 7일, 30일, 90일 이상이 있다. 대여기간이 7일 미만일 경우 할인정책이 없다.
    
    모든 테이블에서 
    자동차 종류가 세단 또는 SUV인 자동차 중
    2022년 11월 1일 부터 ~ 11월 30일까지 대여 가능하고 
    30일간의 대여 금액이 50만원 이상 200만원 미만인
    자동차 ID, 종류, 대여금액 출력
    
    대여 금액을 기준으로 내림차순
    같은 경우 자동차 종류를 기준으로 오름차순
    종류까지 같은 경우 자동차 ID
**/


SELECT 
    CAR_ID, TEMP.CAR_TYPE AS CAR_TYPE, CEIL((DAILY_FEE * 30) * (1-0.01*DISCOUNT_RATE)) AS FEE
FROM (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상') AS TEMP2
JOIN (SELECT
    DISTINCT CAR_RENTAL_COMPANY_CAR.CAR_ID AS CAR_ID, CAR_RENTAL_COMPANY_CAR.DAILY_FEE AS DAILY_FEE, CAR_RENTAL_COMPANY_CAR.CAR_TYPE
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
)) AS TEMP ON TEMP2.CAR_TYPE = TEMP.CAR_TYPE
WHERE 500000 <= (DAILY_FEE * 30) * (1-0.01*DISCOUNT_RATE) AND (DAILY_FEE * 30) * (1-0.01*DISCOUNT_RATE) < 2000000
ORDER BY (DAILY_FEE * 30) * (1-0.01*DISCOUNT_RATE) DESC, TEMP.CAR_TYPE, CAR_ID DESC